# 微信相关配置

# 微信服务地址，如果有微信服务配置自己微信服务的地址
weixin.serverPath: http://api.tfgee.com:9091/baseweixin/api/weixin/

#==========================基本配置=============================
# 微信appid
weixin.appId: wx1b08a5b0b90c4365
# 微信appid
weixin.appSecret: edd5ce61f229bf13e4e4464a49c98468

#========================支付配置================================
#微信支付-绑定的商户id
weixin.payMachId: 123456
#微信支付-商户后台设置的key
weixin.payKey: 123456
#微信支付-支付证书地址
weixin.payQualificationsFile: /data/xxx
#微信支付-支付类型 1、NATIVE（原生） 2、JSAPI（公众号|小程序）3、MWEB（H5）4、APP（app）
weixin.payTradeType: JSAPI
#微信支付-标价币种 
weixin.payFeeType: CNY
#微信支付-回调地址
weixin.payNotifyUrl: /wxPay/unauth/orderCallBack

#========================微信小程序二维码配置=============================
#小程序二维码-宽度
weixin.sqrcodeWidth: 430
#小程序二维码-跳转页面（小程序的页面path）地址
weixin.sqrcodePage: /xxxx/xxxx



