server:
  port: 8080
  servlet:
    context-path: /api
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    encoding: UTF-8
spring:
  #环境
  profiles:
    include: base,datasource,weixin
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: true
      #添加那个目录的文件需要restart
      #additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: src/main
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  message: 
    encoding: UTF-8
  # 所有环境通用的配置，放在这里
  # 404 交给异常处理器处理
  mvc:
    view: #新版本 1.3后可以使用
      suffix: .jsp
      prefix: /WEB-INF/
    throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  #  json时间内容转换，客服端使用JSON提交的时候会按照这个时间格式来转换
  #  如果是表单提交，时间格式请看com.tb.app.configurer.DateConverterConfig
  #  所有的配置最终是合并com.tb.app.common.mapper.JsonMapper这里面的设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # mybatis
# 注意：一定要对应mapper映射xml文件的所在路径
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  # 注意：对应实体类的路径
  #type-aliases-package: com.tb.app.model.qy,com.tb.app.model.sys
  type-aliases-package: com.tb.app.model.**.entity

# 打印sql
logging:
  level:
    com.tb.app.model: debug

#接口根路径
apiPath: /api

#wap跟路径
viewPath: /view

#文件相关
   #文件保存物理路径
userfiles.basedir: /home/tomcat/userfiles
   #文件访问虚拟路径
userfiles.baseUrl: /userfiles
   #文件服务跟地址
userfiles.server: 
