spring:
   redis:
      host: 116.196.78.182
      #Redis服务器连接端口
      port: 6379
      #Redis服务器连接密码（默认为空）
      password: 问我啊
      #连接超时时间（毫秒）
      timeout: 30000
      pool:
         #连接池最大连接数（使用负值表示没有限制）
         max-active: 8
         #连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1
         #连接池中的最大空闲连接
         max-idle: 8
         #连接池中的最小空闲连接
         min-idle: 0